# Generated by Django 5.0.6 on 2024-05-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('confirmpassword', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
